version: "3.8"

services:
  api:
    build: ./api
    container_name: pharmacy-api
    ports:
      - "4000:4000"
    env_file:
      - docker.env
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000
    container_name: pharmacy-frontend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    container_name: pharmacy
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
